events {}

http {
    upstream user_create {
        server 52.2.81.208:5000;
    }
    upstream user_read {
        server 52.2.81.208:5001;
    }
    upstream user_update {
        server 52.2.81.208:5002;
    }
    upstream user_delete {
        server 52.2.81.208:5003;
    }

    upstream user_roles {
        server 52.2.81.208:5004;
    }
    
    upstream user_recovery {
        server 52.2.81.208:5005;
    }
    
    upstream product_catalog {
        server 52.2.81.208:5006;
    }
    upstream inventory {
        server 52.2.81.208:5007;
    }
    upstream order {
        server 52.2.81.208:5008;
    }
    upstream cart {
        server 52.2.81.208:5009;
    }

    server {
        listen 80;

        # USER CREATE
        location /users/create {
            proxy_pass http://user_create/users/create;
        }

        # USER READ
        location /users/read {
            proxy_pass http://user_read/users/read;
        }

        # USER UPDATE
        location /users/update {
            proxy_pass http://user_update/users/update;
        }

        # USER DELETE
        location /users/delete {
            proxy_pass http://user_delete/users/delete;
        }


        # PASSWORD RECOVERY
        location /users/password-recovery {
            proxy_pass http://user_recovery/users/password-recovery;
        }

        # ROLES
        location /users/roles {
            proxy_pass http://user_roles/users/roles;
        }

        # PRODUCTS
        location /products/create {
             proxy_pass http://product_catalog/products/create;
        }

        location /products/list/ {
            proxy_pass http://product_catalog/products/list/;
        }


        # INVENTORY
        location /inventory/add {
            proxy_pass http://inventory/inventory/add;
        }

        location /inventory/list/ {
            proxy_pass http://inventory/inventory/list/;
        }


        # ORDER
        location /orders/create {
             proxy_pass http://order/orders/create;
        }

        location /orders/list/ {
            proxy_pass http://order/orders/list/;
        }


        # CART
        
        location /cart/add {
            proxy_pass http://cart/cart/add;
        }

        location /cart/get/ {
            proxy_pass http://cart/cart/get/;
        }

        location /cart/clear/ {
            proxy_pass http://cart/cart/clear/;
        }




    }
}
