name: CI - QA - User Create v2

on:
  push:
    branches: [ "qa" ]
    paths:
      - 'apps/user/user-create-service/**'
  pull_request:
    branches: [ "qa" ]
    paths:
      - 'apps/user/user-create-service/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd apps/user/user-create-service
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        cd apps/user/user-create-service
        pytest tests/
