name: QA - User Password Recovery Service

on:
  push:
    branches:
      - qa
    paths:
      - 'apps/user/user-password-recovery-service/**'
      - '.github/workflows/qa-user-password-recovery.yml'
  pull_request:
    branches:
      - qa
    paths:
      - 'apps/user/user-password-recovery-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r apps/user/user-password-recovery-service/requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          cd apps/user/user-password-recovery-service
          PYTHONPATH=. pytest tests/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: rommela462
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t rommela462/user-password-recovery-service:qa-latest ./apps/user/user-password-recovery-service
          docker push rommela462/user-password-recovery-service:qa-latest
